PREFIX db: <http://mappings.dbpedia.org/server/ontology/classes/>

select distinct ?name ?population ?area
where { 
    ?country a db:Country .
    ?country db:Name ?name .
    ?country db:Population ?population .
    ?country db:Area ?area .
    filter (?population < 50000)
} 
order by ?area
limit 100 