PREFIX db: <http://mappings.dbpedia.org/server/ontology/classes/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select distinct ?name ?value
where { 
    ?country a db:Country .
    ?country db:Name ?name .
    ?country db:GrossDomesticProduct ?GDP .
    ?GDP rdfs:value ?value .
    ?GDP db:Year 2017 .
} 
order by desc (?value)
limit 10